instance creation
new 
	self error: 'Use #id:name:'